site_name: ParallelChain® Mainnet Documentation
site_url: https://docs.parallelchain.io
repo_name: parallelchain-io/parallelchain-docs
repo_url: https://github.com/parallelchain-io/parallelchain-docs
copyright: ParallelChain Lab 2022
extra:
  homepage: https://www.parallelchain.io/
nav:
  - ParallelChain F: index.md
  - Concepts:
    - Accounts: concepts/accounts.md
    - Block: concepts/block.md
    - Transaction and Receipt: concepts/transaction.md
    - TXPLL: concepts/txpll.md
    - Mempool: concepts/mempool.md
    - Smart Contract: concepts/smartcontract.md
    - Gas: concepts/gas.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - Prepare Environment: getting_started/prepare_env.md
    - Create Account: getting_started/create_account.md
    - Transfer Tokens (EtoE): getting_started/transfer_token.md
    - Deploy Contract (DeployC): getting_started/deploy_contract.md
    - Call Contract (EtoC): getting_started/call_contract.md
    - Transaction Parameters: getting_started/tx_params.md
    - Status Code: getting_started/status_code.md
    - Contract Publishing Service: getting_started/contract_publish.md
  - Smart Contract Development:
    - Install SDK: smart_contract_sdk/installation.md
    - Prepare Environment: smart_contract_sdk/prepare_env.md
    - Develop Contract: smart_contract_sdk/develop_contract.md
    - Build Contract: smart_contract_sdk/build_contract.md
    - Token Standard - PRFC-1: smart_contract_sdk/PRFC1.md
    - Token Standard - PRFC-2: smart_contract_sdk/PRFC2.md
    - Advance: 
      - Contract Methods: smart_contract_sdk/advance/entrypoints.md
      - Contract Storage: smart_contract_sdk/advance/rw_world_state.md
      - Accessing Information About the Blockchain: smart_contract_sdk/advance/params.md
      - Cross Contract Call: smart_contract_sdk/advance/cross_contract.md
      - Transferring Balance: smart_contract_sdk/advance/internal_transaction.md
      - Contract Metadata: smart_contract_sdk/advance/contract_metadata.md
      - Precompiles: smart_contract_sdk/advance/precompiles.md
extra_css:
  - stylesheets/extra.css
theme: 
  name: material
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.top
  logo: img/parallelchain-logo.svg
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
plugins:
  - tags:
      tags_file: tags.md
  - search
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
