site_name: ParallelChain® Mainnet Documentation
site_url: https://docs.parallelchain.io
repo_name: parallelchain-io/parallelchain-docs
repo_url: https://github.com/parallelchain-io/parallelchain-docs
copyright: ParallelChain Lab 2022
nav:
  - Home: index.md
  - ParallelChain Smart Contract Development Kit (SDK): 
    - smart_contract_sdk/index.md
    - Installation: smart_contract_sdk/installation.md
    - Prepare Environment: smart_contract_sdk/prepare_env.md
    - My First Contract: smart_contract_sdk/my_first_contract.md
    - Tutorial - Using The SDK: smart_contract_sdk/sdk_tutorial.md
    - Building and Deploying the Contract: smart_contract_sdk/build_deploy_contract.md
    - Calling a Contract from an Externally Owned Account: smart_contract_sdk/etoc_call.md
    - Creating a Smart Contract from Scratch: smart_contract_sdk/zero_to_hero.md
    - SDK References: smart_contract_sdk/references.md
  - Transaction Receipt and Status: protocol/index.md
  - Faucet: faucet/index.md
  - ParallelChain Light Client: 
    - cli/index.md
    - Installation: cli/installation.md
    - Tutorial: cli/tutorial.md
    - Light Client References: cli/references.md
extra_css:
  - stylesheets/extra.css
theme: 
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.top
  logo: img/parallelchain-logo.svg
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
plugins:
  - tags:
      tags_file: tags.md
  - search
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
